package com.mediasfu.auction

import android.Manifest
import android.app.Activity
import android.content.ClipData
import android.content.ClipboardManager
import android.content.Context
import android.content.pm.PackageManager
import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.activity.compose.setContent
import androidx.activity.result.contract.ActivityResultContracts
import androidx.compose.foundation.background
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.core.content.ContextCompat
import com.mediasfu.sdk.MediaSfuEngine
import com.mediasfu.sdk.methods.MediasfuParameters
import com.mediasfu.sdk.methods.message_methods.SendMessageOptions
import com.mediasfu.sdk.methods.message_methods.sendMessage
import com.mediasfu.sdk.methods.utils.CreateJoinRoomError
import com.mediasfu.sdk.methods.utils.CreateJoinRoomResponse
import com.mediasfu.sdk.methods.utils.CreateJoinRoomResult
import com.mediasfu.sdk.ui.components.display.CardVideoDisplayOptions
import com.mediasfu.sdk.ui.components.display.DefaultCardVideoDisplay
import com.mediasfu.sdk.ui.components.display.renderCompose
import com.mediasfu.sdk.ui.mediasfu.MediasfuGeneric
import com.mediasfu.sdk.ui.mediasfu.MediasfuGenericOptions
import com.mediasfu.sdk.ui.mediasfu.MediasfuGenericState
import com.mediasfu.sdk.webrtc.WebRtcFactory
import com.mediasfu.sdk.webrtc.ScreenCaptureHelper
import java.net.HttpURLConnection
import java.net.URI
import kotlinx.coroutines.CompletableDeferred
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext
import org.json.JSONArray
import org.json.JSONObject

private val Navy=Color(0xFF070D1C);private val Panel=Color(0xFF101B2A);private val Gold=Color(0xFFFFD60A);private val Teal=Color(0xFF35BCB1);private val Muted=Color(0xFF91A4B7)
data class AuctionLot(val title:String,val art:String,val reserve:Int,val current:Int,val bids:Int,val bidder:String,val state:String,val position:Int)
data class AuctionState(val id:String,val hostName:String,val status:String,val lots:List<AuctionLot>){val lot get()=lots.firstOrNull{it.state=="open"}?:lots.lastOrNull()}
data class AuctionIdentity(val name:String,val role:String,val auction:AuctionState?=null,val token:String="",val meetingId:String="",val room:CreateJoinRoomResult?=null)

class AuctionApi(private val origin:String){
 private suspend fun call(path:String,method:String="GET",token:String="",body:JSONObject?=null)=withContext(Dispatchers.IO){val connection=URI.create(origin+path).toURL().openConnection()as HttpURLConnection;try{connection.requestMethod=method;connection.setRequestProperty("Content-Type","application/json");if(token.isNotBlank())connection.setRequestProperty("Authorization","Bearer "+token);if(body!=null){connection.doOutput=true;connection.outputStream.bufferedWriter().use{it.write(body.toString())}};val status=connection.responseCode;val stream=if(status in 200..299)connection.inputStream else connection.errorStream;val payload=JSONObject(stream.bufferedReader().readText());if(status !in 200..299||!payload.optBoolean("success",true))error(payload.optString("error","Auction backend failed"));payload}finally{connection.disconnect()}}
 suspend fun create(name:String):AuctionIdentity{val payload=call("/api/auctions","POST",body=JSONObject().put("hostName",name));return AuctionIdentity(name,"host",payload.getJSONObject("auction").toState(),payload.getString("hostToken"),room=payload.getJSONObject("data").toRoomResult())}
 suspend fun redeem(grant:String,name:String):AuctionIdentity{val payload=call("/api/invites/redeem","POST",body=JSONObject().put("grant",grant).put("displayName",name));return AuctionIdentity(name,payload.getString("role"),payload.getJSONObject("auction").toState(),payload.getString("participantToken"),payload.getString("meetingId"),payload.getJSONObject("data").toRoomResult())}
 suspend fun snapshot(id:String,token:String)=call("/api/auctions/"+id,token=token).getJSONObject("auction").toState()
 suspend fun bid(id:String,token:String,amount:Int)=call("/api/auctions/"+id+"/bids","POST",token,JSONObject().put("amountCents",amount).put("idempotencyKey","bid_"+System.nanoTime())).getJSONObject("state").toState()
 suspend fun settle(id:String,token:String)=call("/api/auctions/"+id+"/settle","POST",token,JSONObject()).getJSONObject("auction").toState()
 suspend fun invite(id:String,token:String,role:String)=call("/api/auctions/"+id+"/invites","POST",token,JSONObject().put("role",role)).getString("grant")
 suspend fun end(id:String,token:String){val value=call("/api/auctions/"+id+"/end","POST",token,JSONObject()).getJSONObject("data");check(value.optString("outcome")=="ended"&&value.optString("residue")=="clear"){"Room cleanup was not confirmed"}}
}
private fun JSONObject.toState():AuctionState{val list=getJSONArray("lots");return AuctionState(getString("id"),getString("hostName"),getString("status"),List(list.length()){list.getJSONObject(it).toLot()})}
private fun JSONObject.toLot()=AuctionLot(getString("title"),optString("art","◆"),getInt("reserveCents"),optInt("highestBidCents"),optInt("bidCount"),optString("highestBidderName"),getString("state"),getInt("position"))
private fun JSONObject.toRoomResult()=CreateJoinRoomResult(data=CreateJoinRoomResponse(message=optString("message","Room ready"),roomName=optString("roomName",optString("meetingID")),secureCode=optString("secureCode").ifBlank{null},publicURL=optString("publicURL",optString("link")),link=optString("link",optString("publicURL")),secret=optString("secret"),success=true),success=true)

class AuctionActivity:ComponentActivity(){
 override fun onCreate(savedInstanceState:Bundle?){super.onCreate(savedInstanceState);val grant=intent?.data?.getQueryParameter("invite").orEmpty();setContent{MaterialTheme(colorScheme=darkColorScheme(primary=Gold,secondary=Teal,background=Navy,surface=Panel)){AuctionRoot(grant)}}}
}
@Composable private fun AuctionRoot(grant:String){val scope=rememberCoroutineScope();val api=remember{AuctionApi(BuildConfig.AUCTION_BACKEND_BASE_URL)};var name by remember{mutableStateOf(if(grant.isBlank())"Auctioneer"else"Bidder1")};var identity by remember{mutableStateOf<AuctionIdentity?>(null)};var busy by remember{mutableStateOf(false)};var notice by remember{mutableStateOf("")};if(identity==null){Box(Modifier.fillMaxSize().background(Navy).padding(28.dp),contentAlignment=Alignment.Center){Column(verticalArrangement=Arrangement.spacedBy(15.dp)){Text("MEDIASFU SOLUTION STARTER",color=Gold,fontWeight=FontWeight.Black);Text(if(grant.isBlank())"Run a live auction"else"Enter the salesroom",color=Color.White,fontSize=40.sp,fontWeight=FontWeight.Black);Text(if(grant.isBlank())"Premium Android media, authoritative bids, and secure room creation."else"Your private invitation decides whether you can bid or watch.",color=Muted);OutlinedTextField(value=name,onValueChange={name=it.take(10)},label={Text("Display name")});Button(enabled=!busy,onClick={scope.launch{busy=true;notice="";runCatching{if(grant.isBlank())AuctionIdentity(name,"host")else api.redeem(grant,name)}.onSuccess{identity=it}.onFailure{notice=it.message?:"Could not enter auction"};busy=false}}){Text(if(busy)"Opening…"else if(grant.isBlank())"Open salesroom →"else"Enter auction →")};if(notice.isNotBlank())Text(notice,color=Color(0xFFFF9CAA))}}}else AuctionEngine(identity!!,api,onExit={identity=null})}

@Composable private fun AuctionEngine(initial:AuctionIdentity,api:AuctionApi,onExit:()->Unit){val context=LocalContext.current;val scope=rememberCoroutineScope();val engine=remember{MediaSfuEngine(deviceProvider={runCatching{WebRtcFactory.createDevice(context)}.getOrNull()})};val parameters=remember(engine){engine.getParameters()};var identity by remember{mutableStateOf(initial)};var auction by remember{mutableStateOf(initial.auction)};var token by remember{mutableStateOf(initial.token)};var notice by remember{mutableStateOf("")};var audioDeferred by remember{mutableStateOf<CompletableDeferred<Boolean>?>(null)};var cameraDeferred by remember{mutableStateOf<CompletableDeferred<Boolean>?>(null)};var screenDeferred by remember{mutableStateOf<CompletableDeferred<Map<String,Any?>?>?>(null)};val audioLauncher=rememberLauncherForActivityResult(ActivityResultContracts.RequestPermission()){granted->parameters.hasAudioPermission=granted;audioDeferred?.complete(granted);audioDeferred=null};val cameraLauncher=rememberLauncherForActivityResult(ActivityResultContracts.RequestPermission()){granted->parameters.hasCameraPermission=granted;cameraDeferred?.complete(granted);cameraDeferred=null};val screenLauncher=rememberLauncherForActivityResult(ActivityResultContracts.StartActivityForResult()){result->val pending=screenDeferred;screenDeferred=null;if(result.resultCode!=Activity.RESULT_OK||result.data==null)pending?.complete(null)else scope.launch{runCatching{ScreenCaptureForegroundService.start(context);mapOf("resultCode" to result.resultCode,"data" to result.data,"onProjectionStopped" to {ScreenCaptureForegroundService.stop(context)})}.onSuccess{pending?.complete(it)}.onFailure{ScreenCaptureForegroundService.stop(context);pending?.complete(null);notice="Android could not start screen capture."}}}
 LaunchedEffect(engine){engine.initializeDevice(context);parameters.hasAudioPermission=ContextCompat.checkSelfPermission(context,Manifest.permission.RECORD_AUDIO)==PackageManager.PERMISSION_GRANTED;parameters.hasCameraPermission=ContextCompat.checkSelfPermission(context,Manifest.permission.CAMERA)==PackageManager.PERMISSION_GRANTED;parameters.requestPermissionAudio=suspend{if(parameters.hasAudioPermission)true else CompletableDeferred<Boolean>().also{audioDeferred=it;audioLauncher.launch(Manifest.permission.RECORD_AUDIO)}.await()};parameters.requestPermissionCamera=suspend{if(parameters.hasCameraPermission)true else CompletableDeferred<Boolean>().also{cameraDeferred=it;cameraLauncher.launch(Manifest.permission.CAMERA)}.await()};parameters.requestScreenCapturePermission=suspend{CompletableDeferred<Map<String,Any?>?>().also{screenDeferred=it;screenLauncher.launch(ScreenCaptureHelper.createPermissionIntent(context))}.await()};parameters.stopScreenCaptureService={ScreenCaptureForegroundService.stop(context)}}
 DisposableEffect(engine){onDispose{audioDeferred?.cancel();cameraDeferred?.cancel();screenDeferred?.cancel();parameters.requestPermissionAudio=null;parameters.requestPermissionCamera=null;parameters.requestScreenCapturePermission=null;parameters.stopScreenCaptureService=null;ScreenCaptureForegroundService.stop(context)}}
 LaunchedEffect(auction?.id,token){while(auction?.id!=null&&token.isNotBlank()){delay(1500);runCatching{api.snapshot(auction!!.id,token)}.onSuccess{auction=it}.onFailure{notice=it.message?:"Refresh failed"}}}
 val isHost=identity.role=="host";val options=remember(identity){MediasfuGenericOptions(connectMediaSFU=true,returnUI=false,sourceParameters=parameters,updateSourceParameters={it.updateIslevel(if(isHost)"2"else if(identity.role=="bidder")"1"else"0")},noUIPreJoinOptionsCreate=if(isHost)mapOf("action" to "create","userName" to identity.name,"duration" to 120,"capacity" to 8,"eventType" to "conference")else null,noUIPreJoinOptionsJoin=if(!isHost)mapOf("action" to "join","userName" to identity.name,"meetingID" to identity.meetingId)else null,createMediaSFURoom={try{api.create(identity.name).also{identity=it;auction=it.auction;token=it.token}.room!!}catch(error:Throwable){notice=error.message?:"Could not create auction";CreateJoinRoomResult(data=CreateJoinRoomError(notice,false),success=false)}},joinMediaSFURoom={identity.room!!},customComponent={state->AuctionSurface(state,parameters,identity,auction,token,api,notice,onNotice={notice=it},onAuction={auction=it},onExit=onExit)})};Box(Modifier.fillMaxSize().background(Navy)){Text("Securing auction room…",color=Muted,modifier=Modifier.align(Alignment.Center));MediasfuGeneric(options,Modifier.fillMaxSize())}}

@Composable private fun AuctionSurface(state:MediasfuGenericState,parameters:MediasfuParameters,identity:AuctionIdentity,auction:AuctionState?,token:String,api:AuctionApi,notice:String,onNotice:(String)->Unit,onAuction:(AuctionState)->Unit,onExit:()->Unit){val scope=rememberCoroutineScope();val context=LocalContext.current;var chat by remember{mutableStateOf("")};val invites=remember{mutableStateListOf<Pair<String,String>>()}
 val screenId=parameters.screenShareIDStream;val liveRemote=parameters.allVideoStreamsState.filter{it.stream!=null};val remote=liveRemote.firstOrNull{it.producerId==screenId}?:liveRemote.firstOrNull();val stream=if(screenId.isNotBlank()&&remote?.producerId==screenId)remote else if(identity.role=="host")parameters.localStreamVideo?.let{com.mediasfu.sdk.model.Stream(producerId="local",stream=it)}else remote;parameters.allAudioStreams.forEach{it.stream?.getAudioTracks()?.forEach{track->track.setEnabled(true)}};val lot=auction?.lot;val participants=parameters.participants.filter{it.name!=identity.name&&it.islevel!="2"};val participantStreams=participants.associateWith{person->liveRemote.firstOrNull{it.name==person.name||it.producerId==person.videoID}};fun fail(error:Throwable){onNotice(error.message?:"Action failed")}
 LazyColumn(Modifier.fillMaxSize().background(Navy).padding(14.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){
  item{Card(colors=CardDefaults.cardColors(Panel)){Row(Modifier.fillMaxWidth().padding(14.dp),horizontalArrangement=Arrangement.SpaceBetween,verticalAlignment=Alignment.CenterVertically){Column{Text("◆ NORTHSTAR AUCTION HOUSE",color=Gold,fontWeight=FontWeight.Black);Text("MediaSFU headless · "+identity.role,color=Muted)};Text(if(parameters.validated)"● LIVE"else"● SECURING",color=if(parameters.validated)Teal else Muted,fontWeight=FontWeight.Black);if(identity.role=="host")Button(onClick={scope.launch{runCatching{api.end(auction!!.id,token)}.onSuccess{onExit()}.onFailure(::fail)}}){Text("End")}}}}
  item{Card(modifier=Modifier.fillMaxWidth().height(330.dp),shape=RoundedCornerShape(18.dp)){if(stream?.stream!=null)DefaultCardVideoDisplay(CardVideoDisplayOptions(videoStream=stream.stream,remoteProducerId=stream.producerId,forceFullDisplay=stream.producerId!=screenId,doMirror=stream.producerId=="local",displayLabel="Auctioneer",showControls=false)).renderCompose()else Box(Modifier.fillMaxSize().background(Panel),contentAlignment=Alignment.Center){Column(horizontalAlignment=Alignment.CenterHorizontally){Surface(shape=CircleShape,color=Color(0xFF153441),modifier=Modifier.size(100.dp)){Box(contentAlignment=Alignment.Center){Text((auction?.hostName?:identity.name).take(1),color=Gold,fontSize=42.sp)}};Text("Camera and mic off",color=Muted)}}}}
  if(identity.role!="viewer")item{Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.Center){OutlinedButton(onClick=state::toggleAudio){Text(if(parameters.audioAlreadyOn)"Mute"else"Unmute")};Spacer(Modifier.width(8.dp));OutlinedButton(onClick=state::toggleVideo){Text(if(parameters.videoAlreadyOn)"Camera off"else"Camera on")};Spacer(Modifier.width(8.dp));OutlinedButton(onClick=state::toggleScreenShare){Text("Share")}}}
  item{Card(colors=CardDefaults.cardColors(Color(0xFF101927))){Column(Modifier.padding(18.dp),verticalArrangement=Arrangement.spacedBy(7.dp)){Text(lot?.art?:"◆",fontSize=72.sp,modifier=Modifier.align(Alignment.CenterHorizontally));Text("NOW BIDDING",color=Gold,fontWeight=FontWeight.Black);Text(lot?.title?:"Preparing lot",fontSize=24.sp,fontWeight=FontWeight.Black);Text("$"+((lot?.current?.takeIf{it>0}?:lot?.reserve?:0)/100),color=Gold,fontSize=36.sp,fontWeight=FontWeight.Black);Text(if(lot?.bidder?.isNotBlank()==true)lot.bidder+" leads · "+lot.bids+" bids"else"Reserve",color=Muted);if(identity.role=="bidder")listOf(2500,10000,50000).forEach{increment->Button(onClick={scope.launch{val amount=maxOf(lot?.reserve?:0,(lot?.current?:0)+increment);runCatching{api.bid(auction!!.id,token,amount)}.onSuccess(onAuction).onFailure(::fail)}}){Text("Bid $"+(maxOf(lot?.reserve?:0,(lot?.current?:0)+increment)/100))}};if(identity.role=="host")Button(onClick={scope.launch{runCatching{api.settle(auction!!.id,token)}.onSuccess(onAuction).onFailure(::fail)}}){Text("🔨 Close lot and advance")};if(identity.role=="viewer")Text("View-only invitation · bidding and publishing are disabled.",color=Muted)}}}
  item{Card(colors=CardDefaults.cardColors(Panel)){Column(Modifier.padding(16.dp)){Text("BIDDING FLOOR",color=Gold,fontWeight=FontWeight.Black);Text("Every participant keeps a card",fontSize=20.sp,fontWeight=FontWeight.Black);if(participants.isEmpty())Text("No bidders on camera yet. Every connected person retains an identity card.",color=Muted);participants.forEach{person->val tile=participantStreams[person];ListItem(headlineContent={Text(person.name)},supportingContent={Text(if(person.videoID!="none")"Camera live"else if(person.audioID!="none")"Mic live · camera off"else"Camera and mic off")},leadingContent={Box(Modifier.size(56.dp)){if(tile?.stream!=null)DefaultCardVideoDisplay(CardVideoDisplayOptions(videoStream=tile.stream,remoteProducerId=tile.producerId,forceFullDisplay=true,doMirror=false,displayLabel=person.name,showControls=false)).renderCompose()else Surface(shape=CircleShape,color=Color(0xFF153441),modifier=Modifier.fillMaxSize()){Box(contentAlignment=Alignment.Center){Text(person.name.take(1),color=Gold)}}}},trailingContent=if(identity.role=="host")({Row{TextButton(onClick={state.muteParticipant(person)}){Text("Mute")};TextButton(onClick={state.removeParticipant(person)}){Text("Remove")}}})else null)}}}}
  item{Card(colors=CardDefaults.cardColors(Color(0xFF101927))){Column(Modifier.padding(16.dp)){Text("SALESROOM CHAT",color=Gold,fontWeight=FontWeight.Black);state.messaging.messages.filter{it.receivers.isEmpty()}.takeLast(8).forEach{Text((if(it.sender==identity.name)"You"else it.sender)+": "+it.message)};if(identity.role!="viewer")Row(verticalAlignment=Alignment.CenterVertically){OutlinedTextField(value=chat,onValueChange={chat=it.take(240)},modifier=Modifier.weight(1f),label={Text("Message the salesroom")});IconButton(onClick={scope.launch{runCatching{sendMessage(SendMessageOptions(member=parameters.member,islevel=parameters.islevel,coHostResponsibility=parameters.coHostResponsibility,coHost=parameters.coHost,chatSetting=parameters.chatSetting,message=chat,roomName=parameters.roomName,messagesLength=parameters.messages.size,receivers=emptyList(),group=true,sender=parameters.member,socket=parameters.socket))}.onSuccess{chat=""}.onFailure(::fail)}}){Text("➤")}}}}}
  if(identity.role=="host"&&auction!=null)item{Card(colors=CardDefaults.cardColors(Panel)){Column(Modifier.padding(16.dp),verticalArrangement=Arrangement.spacedBy(8.dp)){Text("PRIVATE SINGLE-USE INVITES",color=Gold,fontWeight=FontWeight.Black);Text("Bidder links can bid and publish. Viewer links join WebRTC read-only.",color=Muted);Row{Button(onClick={scope.launch{runCatching{api.invite(auction.id,token,"bidder")}.onSuccess{invites.add("bidder" to ("mediasfu-auction://join?invite="+it))}.onFailure(::fail)}}){Text("Bidder link")};Spacer(Modifier.width(8.dp));Button(onClick={scope.launch{runCatching{api.invite(auction.id,token,"viewer")}.onSuccess{invites.add("viewer" to ("mediasfu-auction://join?invite="+it))}.onFailure(::fail)}}){Text("Viewer link")}};invites.forEach{item->ListItem(headlineContent={Text(item.first+" link ready")},supportingContent={Text("Expires in one hour · single use")},trailingContent={IconButton(onClick={val clipboard=context.getSystemService(Context.CLIPBOARD_SERVICE)as ClipboardManager;clipboard.setPrimaryClip(ClipData.newPlainText("Auction invite",item.second))}){Text("Copy")}})}}}}
  if(notice.isNotBlank())item{Text(notice,color=Color(0xFFFF9CAA))}
 }}
