import React, { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { AudioGrid, ModernMediasfuGeneric, getChatMessages, setRoomMediaPolicy, useMediasfuHeadless } from 'mediasfu-reactjs';
import { request } from './api.js';
import { money, nextBid, selectAuctionMedia } from './media.js';
import { createOneShotCleanup, roomConnectionPresentation } from './roomLifecycle.js';
import './recovery.css';

function Video({ stream, kind }) {
  const ref = useRef(null);
  useEffect(() => { const node = ref.current; if (!node || !stream) return; node.srcObject = stream; node.play?.().catch(() => {}); return () => { if (node.srcObject === stream) node.srcObject = null; }; }, [stream]);
  return <video ref={ref} autoPlay playsInline muted={kind === 'local'} className={kind === 'screen' ? 'screen-video' : kind === 'local' ? 'local-video' : ''} />;
}

function Entry({ invite, onReady }) {
  const [name, setName] = useState(invite ? 'Bidder1' : 'Auctioneer'); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const submit = async (event) => { event.preventDefault(); setBusy(true); setError(''); try {
    if (invite) { const value = await request('/api/invites/redeem', { method: 'POST', body: JSON.stringify({ grant: invite, displayName: name }) }); onReady({ role: value.role, displayName: name, auction: value.auction, token: value.participantToken, meetingId: value.meetingId, roomResponse: value.data }); }
    else { onReady({ role: 'host', displayName: name }); }
  } catch (cause) { setError(cause.message); } finally { setBusy(false); } };
  return <main className="entry-shell"><section className="entry-card"><span className="eyebrow">MediaSFU solution starter</span><div className="gavel">◆</div><h1>{invite ? 'Enter the salesroom' : 'Run a live auction'}</h1><p>{invite ? 'Your private invitation decides whether you can bid or watch.' : 'Premium realtime media, bidder controls, and authoritative bidding—without exposing API credentials.'}</p><form onSubmit={submit}><label>Display name<input value={name} maxLength={10} pattern="[A-Za-z0-9]{2,10}" onChange={(event) => setName(event.target.value)} /></label>{error && <p className="error">{error}</p>}<button disabled={busy}>{busy ? 'Opening…' : invite ? 'Enter auction' : 'Open auctioneer console'} <span>→</span></button></form><small>Payments and settlement are deliberately outside this starter.</small></section></main>;
}

function AuctionCard({ auction, role, onBid, onSettle, busy }) {
  const lot = auction?.lots?.find((item) => item.state === 'open') || auction?.lots?.at(-1); const [tick, setTick] = useState(Date.now());
  useEffect(() => { const timer = setInterval(() => setTick(Date.now()), 1000); return () => clearInterval(timer); }, []);
  const remaining = Math.max(0, Math.ceil(((lot?.deadlineAt || tick) - tick) / 1000));
  return <section className="lot-card"><div className="lot-art" aria-hidden>{lot?.art || '◆'}<span>LOT {Number(lot?.position || 0) + 1} OF {auction?.lots?.length || 3}</span></div><div className="lot-copy"><div className="lot-heading"><div><span className="eyebrow">Now bidding</span><h2>{lot?.title || 'Preparing the first lot'}</h2></div><span className={`timer ${remaining <= 10 ? 'urgent' : ''}`}>◷ {remaining}s</span></div><div className="bid-price"><span>Current bid</span><strong>{money(lot?.highestBidCents || lot?.reserveCents)}</strong><small>{lot?.highestBidderName ? `${lot.highestBidderName} leads · ${lot.bidCount} bids` : `Reserve ${money(lot?.reserveCents)}`}</small></div>{role === 'bidder' && <div className="quick-bids">{[2500,10000,50000].map((increment) => <button disabled={busy || auction?.status !== 'open'} key={increment} onClick={() => onBid(nextBid(lot, increment))}>Bid {money(nextBid(lot, increment))}</button>)}</div>}{role === 'viewer' && <p className="viewer-note">View-only invitation · live bidding controls are hidden</p>}{role === 'host' && <button className="settle" disabled={busy || auction?.status !== 'open'} onClick={onSettle}>🔨 Close lot and advance</button>}</div></section>;
}

function Room({ session, onExit }) {
  const room = useMediasfuHeadless(); const [auction, setAuction] = useState(session.auction || null); const [auth, setAuth] = useState(session.token || ''); const [roomResponse, setRoomResponse] = useState(session.roomResponse || null); const [busy, setBusy] = useState(false); const [notice, setNotice] = useState(''); const [connectionFailure, setConnectionFailure] = useState(''); const [clock, setClock] = useState(Date.now()); const [invites, setInvites] = useState([]); const [chatDraft, setChatDraft] = useState(''); const [floorEnabled, setFloorEnabled] = useState(true); const [biddersCanProduce, setBiddersCanProduce] = useState(true); const [seatCount, setSeatCount] = useState(4); const roomRequest = useRef(null); const roleSet = useRef(false); const connectionStartedAt = useRef(Date.now()); const wasReady = useRef(false);
  const isHost = session.role === 'host';
  const preJoinOptions = useMemo(() => isHost ? { action: 'create', userName: session.displayName, duration: 120, capacity: 8, eventType: 'conference' } : { action: 'join', userName: session.displayName, meetingID: session.meetingId }, [isHost, session]);
  const createRoom = async () => { if (!roomRequest.current) roomRequest.current = request('/api/auctions', { method: 'POST', body: JSON.stringify({ hostName: session.displayName }) }); try { const value = await roomRequest.current; setAuction(value.auction); setAuth(value.hostToken); setRoomResponse(value.data); return { success: true, data: value.data }; } catch (error) { setConnectionFailure(error.message); setNotice(error.message); return { success: false, data: { error: error.message } }; } };
  const joinRoom = async () => ({ success: true, data: roomResponse });
  const updateSource = (parameters) => { room.updateSourceParameters(parameters || {}); if (!roleSet.current && parameters?.updateIslevel) { parameters.updateIslevel(isHost ? '2' : '1'); roleSet.current = true; } };
  useEffect(() => { if (room.ready) wasReady.current = true; else { const timer = setInterval(() => setClock(Date.now()), 1000); return () => clearInterval(timer); } }, [room.ready]);
  useEffect(() => { if (!auction?.id || !auth) return; let active = true; const poll = async () => { try { const value = await request(`/api/auctions/${auction.id}`, { token: auth }); if (!active) return; setAuction(value.auction); if (value.auction?.status === 'ended') setConnectionFailure('This auction has ended. Return to the start screen to open or join another room.'); } catch (error) { if (!active) return; setNotice(error.message); if (error.status === 404 || error.status === 410) setConnectionFailure('This auction is no longer available. Return to the start screen to continue.'); } }; void poll(); const timer = setInterval(poll, 1500); return () => { active = false; clearInterval(timer); }; }, [auction?.id, auth]);
  useEffect(() => { if (!isHost || !room.ready) return; const allow = floorEnabled && biddersCanProduce ? 'allow' : 'disallow'; void setRoomMediaPolicy({ parameters: room.parameters, audio: allow, video: allow }).then((result) => { if (!result?.ok) setNotice(result?.error || 'Bidder media policy could not be updated.'); }); }, [isHost, room.ready, floorEnabled, biddersCanProduce]);
  const media = selectAuctionMedia(room, session.role); const lot = auction?.lots?.find((item) => item.state === 'open');
  const connection = roomConnectionPresentation({ ready: room.ready, readinessReason: room.readiness.reason, failure: connectionFailure, wasReady: wasReady.current, elapsedMs: clock - connectionStartedAt.current });
  const lifecycleCleanup = useMemo(() => isHost && auction?.id && auth ? createOneShotCleanup(() => request(`/api/auctions/${auction.id}/abandon`, { method: 'POST', token: auth, body: '{}', keepalive: true })) : null, [isHost, auction?.id, auth]);
  useEffect(() => { if (!lifecycleCleanup) return; const cleanup = () => lifecycleCleanup.run(); window.addEventListener('pagehide', cleanup); return () => window.removeEventListener('pagehide', cleanup); }, [lifecycleCleanup]);
  const messages = getChatMessages({ parameters: room.parameters, scope: 'group' }).slice(-8); const floorParticipants = room.participants.filter((participant) => !participant.isSelf && !participant.isHost);
  const action = async (work) => { setBusy(true); setNotice(''); try { await work(); } catch (error) { setNotice(error.message); } finally { setBusy(false); } };
  const bid = (amountCents) => action(async () => { const value = await request(`/api/auctions/${auction.id}/bids`, { method: 'POST', token: auth, body: JSON.stringify({ amountCents, idempotencyKey: `bid_${crypto.randomUUID().replaceAll('-', '')}` }) }); setAuction(value.state); });
  const settle = () => action(async () => { const value = await request(`/api/auctions/${auction.id}/settle`, { method: 'POST', token: auth, body: '{}' }); setAuction(value.auction); });
  const invite = (role) => action(async () => { if (role === 'bidder' && (!floorEnabled || invites.filter((item) => item.role === 'bidder').length >= seatCount)) throw new Error(`The floor is ${floorEnabled ? `limited to ${seatCount} bidder seats` : 'closed'}.`); const value = await request(`/api/auctions/${auction.id}/invites`, { method: 'POST', token: auth, body: JSON.stringify({ role }) }); const url = `${location.origin}${location.pathname}?invite=${encodeURIComponent(value.grant)}`; setInvites((current) => [...current, { role, url, id: crypto.randomUUID() }]); });
  const sendChat = (event) => { event.preventDefault(); const message = chatDraft.trim(); if (!message || session.role === 'viewer') return; action(async () => { const result = await room.controls.sendChat(message, { group: true }); if (!result.ok) throw new Error(result.error || 'Message could not be sent.'); setChatDraft(''); }); };
  const moderate = (kind, participant) => action(async () => { const operation = kind === 'mute' ? room.moderation.muteParticipant(participant.name) : room.moderation.removeParticipant(participant.name); const result = await operation; if (!result.ok) throw new Error(result.error || `Could not ${kind} ${participant.name}.`); });
  const recover = () => action(async () => { lifecycleCleanup?.run(); await room.controls.leave(false, false).catch(() => {}); onExit(); });
  const end = () => action(async () => { const value = await request(`/api/auctions/${auction.id}/end`, { method: 'POST', token: auth, body: '{}' }); if (value.data.outcome !== 'ended' || value.data.residue !== 'clear') throw new Error('Room cleanup is not confirmed.'); lifecycleCleanup?.markHandled(); await room.controls.leave().catch(() => {}); onExit(); });
  return <><div className="sdk-engine" aria-hidden><ModernMediasfuGeneric connectMediaSFU returnUI={false} noUIPreJoinOptions={preJoinOptions} createMediaSFURoom={createRoom} joinMediaSFURoom={joinRoom} sourceParameters={room.sourceParameters} updateSourceParameters={updateSource} onMediaChanged={room.onMediaChanged} /></div><main className="auction-shell"><header className="topbar"><div className="brand"><span>◆</span><div><strong>Northstar Auction House</strong><small>Powered by MediaSFU · headless realtime</small></div></div><div className="authority"><span className={connection.state}><i />{connection.label}</span><b>{session.role.toUpperCase()}</b>{isHost && <button onClick={end}>End auction</button>}</div></header>
  <section className="status-strip"><span>{connection.state === 'unavailable' ? 'CONNECTION ATTENTION' : 'LIVE AUCTION'}</span><strong>{lot ? `Lot ${lot.position + 1} of ${auction?.lots?.length || 3}` : 'Complete'}</strong><small>{connection.detail}</small></section>
  {connection.state === 'unavailable' && <section className="recovery-panel" role="alert"><div><strong>The salesroom is no longer connected.</strong><span>Your auction data is safe in the starter backend. Return to start to create or join an available room.</span></div><button onClick={recover} disabled={busy}>Return to start</button></section>}
  <section className="salesroom"><article className="stage-card"><div className={`media-frame ${media.primary?.kind || 'identity'}`}>{media.primary ? <Video stream={media.primary.stream} kind={media.primary.kind} /> : <div className="identity"><span>{session.role === 'host' ? session.displayName[0] : auction?.hostName?.[0] || 'A'}</span><strong>{session.role === 'host' ? session.displayName : auction?.hostName || 'Auctioneer'}</strong><small>Camera and mic off</small></div>}<div className="media-badges"><b>Auctioneer</b><span>{media.primary ? media.primary.kind === 'screen' ? 'Screen live' : 'Camera live' : 'Camera off'}</span><span>{room.micOn ? 'Mic live' : 'Mic off'}</span></div></div><div className="media-controls">{session.role !== 'viewer' && <><button disabled={!room.ready} onClick={() => action(room.controls.toggleMic)}>{room.micOn ? '● Mute' : '○ Unmute'}</button><button disabled={!room.ready} onClick={() => action(room.controls.toggleCamera)}>▰ {room.cameraOn ? 'Camera off' : 'Camera on'}</button><button disabled={!room.ready} onClick={() => action(room.controls.toggleScreenShare)}>⇧ Share</button></>}</div></article><AuctionCard auction={auction} role={session.role} onBid={bid} onSettle={settle} busy={busy} /></section>
  <section className="floor-chat"><section className="bidder-floor"><div><span className="eyebrow">Bidding floor</span><h2>Live seats</h2></div><ul>{floorEnabled && floorParticipants.length ? floorParticipants.slice(0, seatCount).map((participant) => { const entry = room.remoteVideos.find((video) => video.producerId === participant.videoProducerId); return <li key={participant.name}>{entry?.stream && participant.hasVideo ? <Video stream={entry.stream} kind="remote"/> : <div className="seat-identity"><b>{participant.name.slice(0,1).toUpperCase()}</b><small>{participant.hasAudio ? 'Mic live · camera off' : 'Camera and mic off'}</small></div>}<span>{participant.name}</span>{isHost && room.moderation.permissions.canModerate && <span className="moderate"><button onClick={() => moderate('mute', participant)} title={`Mute ${participant.name}`}>◉</button><button onClick={() => moderate('remove', participant)} title={`Remove ${participant.name}`}>×</button></span>}</li>; }) : <li className="empty-seat"><span>+</span><strong>{floorEnabled ? 'No bidders on camera yet' : 'Bidder floor is closed'}</strong><small>Every connected participant keeps a visible seat.</small></li>}</ul></section><section className="chat-panel"><div><span className="eyebrow">Salesroom chat</span><h2>{session.role === 'viewer' ? 'Read-only room feed' : 'Room conversation'}</h2></div><ol>{messages.length ? messages.map((message, index) => <li key={`${message.timestamp}-${index}`}><b>{message.mine ? 'You' : message.sender}</b><span>{message.message}</span></li>) : <li className="chat-empty">Messages from the live room appear here.</li>}</ol>{session.role !== 'viewer' && <form onSubmit={sendChat}><input value={chatDraft} maxLength={240} onChange={(event) => setChatDraft(event.target.value)} placeholder="Message the salesroom"/><button disabled={!room.ready || busy}>Send</button></form>}</section></section>
  {isHost && auction?.id && <section className="invite-panel"><div><span className="eyebrow">Bring people in</span><h2>Private, single-use invitations</h2><p>Bidder links join realtime WebRTC, can bid, and may publish if allowed. Viewer links currently join realtime WebRTC in read-only mode. HLS output is not claimed until a standalone broker is wired and observed.</p><div className="floor-settings"><label><input type="checkbox" checked={floorEnabled} onChange={(event) => setFloorEnabled(event.target.checked)}/> Bidder floor open</label><label><input type="checkbox" checked={biddersCanProduce} disabled={!floorEnabled} onChange={(event) => setBiddersCanProduce(event.target.checked)}/> Bidders may publish camera/mic</label><label>Seats <select value={seatCount} onChange={(event) => setSeatCount(Number(event.target.value))}>{[2,3,4,6].map((count) => <option key={count}>{count}</option>)}</select></label><label>Audience <select value="webrtc" disabled><option>WebRTC (available)</option><option>HLS (broker required)</option></select></label></div></div><div className="invite-actions"><button onClick={() => invite('bidder')}>Create bidder link</button><button onClick={() => invite('viewer')}>Create WebRTC viewer link</button></div>{invites.length > 0 && <ol>{invites.map((item) => <li key={item.id}><span><b>{item.role === 'bidder' ? 'Bidder' : 'WebRTC viewer'} link ready</b><small>Expires in one hour · single use</small></span><span className="invite-link-actions"><a href={item.url} target="_blank" rel="noreferrer">Open invite</a><button onClick={() => navigator.clipboard.writeText(item.url)}>Copy link</button></span></li>)}</ol>}</section>}
  {notice && <p className="notice" role="status">{notice}</p>}<div className="audio-grid" aria-hidden><AudioGrid componentsToRender={room.audioComponents} /></div><footer><span><b>Real here</b> MediaSFU media, bid ordering, countdown, anti-snipe extension, opaque invites, and confirmed teardown.</span><span><b>Bring your systems</b> Payments, inventory, fulfilment, tax, and legal settlement.</span></footer></main></>;
}

export default function App() {
  const invite = new URLSearchParams(location.search).get('invite'); const [session, setSession] = useState(null);
  return session ? <Room session={session} onExit={() => { history.replaceState({}, '', location.pathname); setSession(null); }} /> : <Entry invite={invite} onReady={setSession} />;
}
