/* global globalThis */
import React,{useEffect,useMemo,useRef,useState}from'react';
import{Linking,Platform,Pressable,SafeAreaView,ScrollView,StyleSheet,Text,TextInput,View}from'react-native';
import Clipboard from'@react-native-clipboard/clipboard';
import{AudioGrid,CardVideoDisplay,ModernMediasfuGeneric,useMediasfuHeadless}from'mediasfu-reactnative';
import{invitationUrl,liveVideo,money}from'./auctionUtils';

const API=globalThis.__AUCTION_API_URL__||(Platform.OS==='android'?'http://10.0.2.2:8791':'http://127.0.0.1:8791');
async function api(path,options={}){const response=await fetch(API+path,{...options,headers:{'content-type':'application/json',...(options.token?{authorization:'Bearer '+options.token}:{})}});const value=await response.json();if(!response.ok||value.success===false)throw new Error(value.error||'Request failed');return value}
/** @type {'create'} */
const CREATE_ACTION='create';
/** @type {'join'} */
const JOIN_ACTION='join';
/** @type {'conference'} */
const CONFERENCE_EVENT='conference';

function Room({identity,onExit}){
 const room=useMediasfuHeadless();const[auction,setAuction]=useState(identity.auction||null),[token,setToken]=useState(identity.token||''),[roomData,setRoomData]=useState(identity.roomData||null),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[invites,setInvites]=useState([]),[chatDraft,setChatDraft]=useState('');
 const requestRef=useRef(null),roleSet=useRef(false);const host=identity.role==='host';
 const lot=auction?.lots?.find(item=>item.state==='open')||auction?.lots?.at(-1);
 const screen=room.screenShare?.stream&&liveVideo(room.screenShare.stream)?room.screenShare.stream:null;
 const remoteVideos=(room.remoteVideos||[]).filter(item=>item?.stream&&liveVideo(item.stream));
 const local=room.localVideo&&liveVideo(room.localVideo)?room.localVideo:null;
 const primary=screen||(host?local:remoteVideos[0]?.stream)||null;
 const primaryKind=screen?'screen':host?'local':'remote';
 const primaryEntry=!host&&!screen?remoteVideos[0]:null;
 const messages=(Array.isArray(room.parameters?.messages)?room.parameters.messages:[]).filter(item=>!item.receivers?.length).slice(-8);
 const participants=(room.participants||[]).filter(item=>!item.isSelf&&!item.isHost);
 const preJoin=useMemo(()=>host?{action:CREATE_ACTION,userName:identity.name,duration:120,capacity:8,eventType:CONFERENCE_EVENT}:{action:JOIN_ACTION,userName:identity.name,meetingID:identity.meetingId},[host,identity]);
 const createRoom=async()=>{try{if(!requestRef.current)requestRef.current=api('/api/auctions',{method:'POST',body:JSON.stringify({hostName:identity.name})});const value=await requestRef.current;setAuction(value.auction);setToken(value.hostToken);setRoomData(value.data);return{success:true,data:value.data}}catch(error){setNotice(error.message);return{success:false,data:{error:error.message}}}};
 const joinRoom=async()=>({success:true,data:roomData});
 const published=parameters=>{room.updateSourceParameters(parameters||{});if(!roleSet.current&&parameters?.updateIslevel){parameters.updateIslevel(host?'2':identity.role==='bidder'?'1':'0');roleSet.current=true}};
 useEffect(()=>{if(!auction?.id||!token)return;let active=true;const refresh=()=>api('/api/auctions/'+auction.id,{token}).then(value=>{if(active)setAuction(value.auction)}).catch(error=>{if(active)setNotice(error.message)});const timer=setInterval(refresh,1500);return()=>{active=false;clearInterval(timer)}},[auction?.id,token]);
 const run=async work=>{setBusy(true);setNotice('');try{const result=await work();if(result&&result.ok===false)throw new Error(result.error||'Action failed')}catch(error){setNotice(error.message)}finally{setBusy(false)}};
 const bid=increment=>run(async()=>{const amount=Math.max(lot?.reserveCents||0,(lot?.highestBidCents||0)+increment);const value=await api('/api/auctions/'+auction.id+'/bids',{method:'POST',token,body:JSON.stringify({amountCents:amount,idempotencyKey:'bid_'+Date.now()+'_'+Math.random().toString(36).slice(2)})});setAuction(value.state)});
 const settle=()=>run(async()=>setAuction((await api('/api/auctions/'+auction.id+'/settle',{method:'POST',token,body:'{}'})).auction));
 const invite=role=>run(async()=>{const value=await api('/api/auctions/'+auction.id+'/invites',{method:'POST',token,body:JSON.stringify({role})});setInvites(current=>[...current,{role,url:invitationUrl(value.grant)}])});
 const sendChat=()=>{const message=chatDraft.trim();if(!message||identity.role==='viewer')return;run(async()=>{const result=await room.controls.sendChat(message,{group:true});if(!result.ok)throw new Error(result.error||'Message could not be sent');setChatDraft('')})};
 const moderate=(kind,person)=>run(()=>kind==='mute'?room.moderation.muteParticipant(person.name):room.moderation.removeParticipant(person.name));
 const end=()=>run(async()=>{const value=await api('/api/auctions/'+auction.id+'/end',{method:'POST',token,body:'{}'});if(value.data?.outcome!=='ended'||value.data?.residue!=='clear')throw new Error('Room cleanup was not confirmed');await room.controls.leave(false,true).catch(()=>{});onExit()});
 return <SafeAreaView style={s.safe}><View style={s.engine}><ModernMediasfuGeneric connectMediaSFU returnUI={false} noUIPreJoinOptions={preJoin} createMediaSFURoom={createRoom} joinMediaSFURoom={joinRoom} sourceParameters={room.sourceParameters} updateSourceParameters={published} onMediaChanged={room.onMediaChanged}/></View><ScrollView contentContainerStyle={s.page}>
  <View style={s.header}><View><Text style={s.brand}>◆ NORTHSTAR AUCTION HOUSE</Text><Text style={s.muted}>MediaSFU headless · {identity.role}</Text></View><Text style={room.ready?s.live:s.wait}>● {room.ready?'LIVE':'SECURING'}</Text>{host?<Pressable style={s.danger} onPress={end} disabled={busy}><Text style={s.buttonText}>End</Text></Pressable>:null}</View>
  <View style={s.stage}>{primary?<CardVideoDisplay remoteProducerId={primaryEntry?.producerId||primaryKind} eventType="conference" forceFullDisplay={primaryKind!=='screen'} videoStream={/** @type {any} */ (primary)} doMirror={primaryKind==='local'} backgroundColor="#091521" style={s.video}/>:<View style={s.identity}><Text style={s.avatar}>{(auction?.hostName||identity.name)[0]}</Text><Text style={s.title}>{auction?.hostName||identity.name}</Text><Text style={s.muted}>Camera and mic off</Text></View>}<Text style={s.badge}>Auctioneer · {screen?'Screen live':primary?'Camera live':'Camera off'}</Text></View>
  {identity.role!=='viewer'?<View style={s.controls}><Action label={room.micOn?'Mute':'Unmute'} disabled={!room.ready} onPress={()=>run(room.controls.toggleMic)}/><Action label={room.cameraOn?'Camera off':'Camera on'} disabled={!room.ready} onPress={()=>run(room.controls.toggleCamera)}/><Action label="Share" disabled={!room.ready} onPress={()=>run(room.controls.toggleScreenShare)}/></View>:null}
  <View style={s.lot}><Text style={s.art}>{lot?.art||'◆'}</Text><Text style={s.gold}>LOT {(lot?.position||0)+1} · NOW BIDDING</Text><Text style={s.title}>{lot?.title||'Preparing lot'}</Text><Text style={s.price}>{money(lot?.highestBidCents||lot?.reserveCents)}</Text><Text style={s.muted}>{lot?.highestBidderName?lot.highestBidderName+' leads · '+lot.bidCount+' bids':'Reserve '+money(lot?.reserveCents)}</Text>{identity.role==='bidder'?[2500,10000,50000].map(value=><Primary key={value} label={'Bid '+money(Math.max(lot?.reserveCents||0,(lot?.highestBidCents||0)+value))} disabled={busy||auction?.status!=='open'} onPress={()=>bid(value)}/>):null}{host?<Primary label="🔨 Close lot and advance" disabled={busy||auction?.status!=='open'} onPress={settle}/>:null}{identity.role==='viewer'?<Text style={s.muted}>View-only invitation · bidding and publishing are disabled.</Text>:null}</View>
  <View style={s.floor}><Text style={s.gold}>BIDDING FLOOR</Text><Text style={s.title}>Every participant keeps a card</Text>{participants.length?participants.map(person=>{const video=remoteVideos.find(item=>item.producerId===person.videoProducerId);return <View key={person.name} style={s.seat}>{video?.stream&&person.hasVideo?<CardVideoDisplay remoteProducerId={video.producerId} eventType="conference" forceFullDisplay videoStream={/** @type {any} */ (video.stream)} doMirror={false} backgroundColor="#091521" style={s.seatVideo}/>:<Text style={s.avatarSmall}>{person.name[0]}</Text>}<View style={s.grow}><Text style={s.buttonText}>{person.name}</Text><Text style={s.muted}>{person.hasVideo?'Camera live':person.hasAudio?'Mic live · camera off':'Camera and mic off'}</Text></View>{host&&room.moderation.permissions.canManageParticipants?<View><Action label="Mute" onPress={()=>moderate('mute',person)}/><Action label="Remove" onPress={()=>moderate('remove',person)}/></View>:null}</View>}):<Text style={s.muted}>No bidders on camera yet. Every connected person retains an identity card.</Text>}</View>
  <View style={s.panel}><Text style={s.gold}>SALESROOM CHAT</Text>{messages.length?messages.map((item,index)=><View key={(item.timestamp||'m')+index} style={s.message}><Text style={s.buttonText}>{item.sender===room.parameters?.member?'You':item.sender}</Text><Text style={s.muted}>{item.message}</Text></View>):<Text style={s.muted}>Messages from the live room appear here.</Text>}{identity.role!=='viewer'?<View style={s.chatRow}><TextInput value={chatDraft} onChangeText={setChatDraft} maxLength={240} placeholder="Message the salesroom" placeholderTextColor="#718599" style={s.input}/><Action label="Send" disabled={!room.ready||busy} onPress={sendChat}/></View>:null}</View>
  {host&&auction?.id?<View style={s.panel}><Text style={s.gold}>PRIVATE SINGLE-USE INVITES</Text><Text style={s.muted}>Bidder links can bid and publish. Viewer links join WebRTC read-only.</Text><View style={s.controls}><Primary label="Bidder link" onPress={()=>invite('bidder')}/><Primary label="Viewer link" onPress={()=>invite('viewer')}/></View>{invites.map(item=><Pressable key={item.url} style={s.invite} onPress={()=>Clipboard.setString(item.url)}><Text style={s.buttonText}>{item.role} link ready</Text><Text style={s.muted}>Tap to copy · expires in one hour · single use</Text></Pressable>)}</View>:null}
  {notice?<Text style={s.notice}>{notice}</Text>:null}<View style={s.engine}><AudioGrid componentsToRender={room.audioComponents}/></View>
 </ScrollView></SafeAreaView>
}
function Action({label,...props}){return <Pressable style={s.secondary}{...props}><Text style={s.buttonText}>{label}</Text></Pressable>}
function Primary({label,...props}){return <Pressable style={s.bid}{...props}><Text style={s.bidText}>{label}</Text></Pressable>}
export default function AuctionApp(){const[name,setName]=useState('Auctioneer'),[identity,setIdentity]=useState(null),[notice,setNotice]=useState(''),[starting,setStarting]=useState(false),[grant,setGrant]=useState('');useEffect(()=>{Linking.getInitialURL().then(url=>{const value=url?new URL(url).searchParams.get('invite')||'':'';setGrant(value);if(value)setName('Bidder1')}).catch(()=>{})},[]);const start=async()=>{setStarting(true);setNotice('');try{if(grant){const value=await api('/api/invites/redeem',{method:'POST',body:JSON.stringify({grant,displayName:name})});setIdentity({name,role:value.role,auction:value.auction,token:value.participantToken,meetingId:value.meetingId,roomData:value.data})}else setIdentity({name,role:'host'})}catch(error){setNotice(error.message)}finally{setStarting(false)}};return identity?<Room identity={identity} onExit={()=>setIdentity(null)}/>:<SafeAreaView style={s.safe}><View style={s.entry}><Text style={s.gold}>MEDIASFU SOLUTION STARTER</Text><Text style={s.hero}>{grant?'Enter the salesroom':'Run a live auction'}</Text><Text style={s.muted}>{grant?'Your private invitation decides whether you can bid or watch.':'Premium native media, authoritative bids, and secure room creation.'}</Text><TextInput value={name} maxLength={10} onChangeText={setName} style={s.input} placeholder="Display name" placeholderTextColor="#718599"/><Primary label={starting?'Opening…':grant?'Enter auction →':'Open salesroom →'} onPress={start} disabled={starting}/>{notice?<Text style={s.notice}>{notice}</Text>:null}</View></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#070d1c'},engine:{width:1,height:1,overflow:'hidden'},page:{padding:14,gap:10},entry:{flex:1,justifyContent:'center',padding:28,gap:16},header:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',gap:8,padding:12,borderRadius:14,backgroundColor:'#101b2a'},brand:{color:'#ffd60a',fontSize:12,fontWeight:'900'},gold:{color:'#ffd60a',fontSize:11,fontWeight:'900',letterSpacing:1.2},muted:{color:'#91a4b7',fontSize:12},live:{color:'#5ce0d3',fontWeight:'900'},wait:{color:'#91a4b7',fontWeight:'900'},stage:{minHeight:300,borderRadius:18,overflow:'hidden',backgroundColor:'#0b1725'},video:{width:'100%',height:300},identity:{height:300,alignItems:'center',justifyContent:'center',gap:6},avatar:{width:90,height:90,borderRadius:45,textAlign:'center',textAlignVertical:'center',backgroundColor:'#12323b',borderWidth:2,borderColor:'#35bcb1',color:'#ffd60a',fontSize:42,fontWeight:'900'},badge:{position:'absolute',left:12,bottom:12,color:'#fff',padding:7,borderRadius:20,backgroundColor:'#07101bd9'},controls:{flexDirection:'row',flexWrap:'wrap',justifyContent:'center',gap:8},secondary:{padding:10,borderWidth:1,borderColor:'#315267',borderRadius:10,backgroundColor:'#102131'},danger:{padding:10,borderRadius:10,backgroundColor:'#401521'},buttonText:{color:'#f8fbff',fontWeight:'800'},lot:{padding:18,gap:7,borderWidth:1,borderColor:'#5b4a1d',borderRadius:18,backgroundColor:'#101927'},art:{fontSize:72,textAlign:'center'},title:{color:'#f8fbff',fontSize:21,fontWeight:'900'},hero:{color:'#f8fbff',fontSize:38,fontWeight:'900'},price:{color:'#ffd60a',fontSize:34,fontWeight:'900'},bid:{padding:14,borderRadius:11,backgroundColor:'#ffd60a',alignItems:'center',minWidth:120},bidText:{color:'#08121b',fontWeight:'900'},floor:{padding:16,gap:9,borderRadius:16,backgroundColor:'#101b2a'},panel:{padding:16,gap:10,borderWidth:1,borderColor:'#284455',borderRadius:16,backgroundColor:'#101927'},seat:{flexDirection:'row',gap:10,alignItems:'center',padding:9,borderRadius:10,backgroundColor:'#0a1622'},seatVideo:{width:72,height:54,borderRadius:8},avatarSmall:{width:42,height:42,borderRadius:21,textAlign:'center',textAlignVertical:'center',color:'#ffd60a',backgroundColor:'#153441',fontWeight:'900'},grow:{flex:1},message:{flexDirection:'row',gap:8,paddingVertical:5},chatRow:{flexDirection:'row',alignItems:'center',gap:8},input:{flex:1,padding:14,borderWidth:1,borderColor:'#294858',borderRadius:10,color:'#fff',backgroundColor:'#091521'},invite:{padding:10,borderRadius:10,backgroundColor:'#0a1622'},notice:{padding:10,borderRadius:8,color:'#ffdfe4',backgroundColor:'#401521'}});
